[package]
name = "hello"
version = "0.1.0"
authors = ["bj"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hello"
crate-type = ["dylib"]

[dependencies.cpython]
version = "0.2"
features = ["extension-module"]
